project:
  type: website
  output-dir: docs
  resources: 
    - files/*

website:
  favicon: assets/WAM-logo.png
  navbar:
    logo: assets/WAM-logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Why web archives?

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true